name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (no install scripts)
        run: npm ci --ignore-scripts

      - name: Build (tsc)
        run: npm run compile

      - name: Package
        run: npx vsce package

      - name: Upload .vsix artifact
        uses: actions/upload-artifact@v4
        with:
          name: docusnap-assets-vsix
          path: "*.vsix"

      - name: Publish to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: npx vsce publish -p "$VSCE_TOKEN"
